dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  consumer:
    check: false
  protocol:
    name: dubbo
    port: 21881
  provider:
    timeout: 3000
    version: 1.0.0
  reference:
    check: false
  registry:
    address: nacos://${nacos.server-addr}?namespace=${nacos.namespace}
    parameters:
      check: false
  scan:
    base-packages: com.pajk.trade.service
logging:
  level:
    com:
      pajk:
        trade: DEBUG
    org:
      apache:
        dubbo: DEBUG
    root: INFO
mcp:
  app-name: ${spring.application.name}
  config-group: ${nacos.mcp.group}
  timeout-ms: 3000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pajk.trade.entity
nacos:
  mcp:
    domain: 订单,交易
    enabled: true
    group: MCP_GROUP
    protocal: MCP
    version: 1.0.0
  namespace: public
  server-addr: 127.0.0.1:8848
server:
  port: 8181
spring:
  application:
    name: tradeCenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/tradecenter?useSSL=false&characterEncoding=utf-8
    username: root
