dubbo:
  application:
    name: itemCenter
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.pajk.item.service
logging:
  level:
    com:
      pajk:
        item: DEBUG
    root: INFO
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pajk.item.entity
server:
  port: 8083
spring:
  application:
    name: itemCenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/itemcenter?useSSL=false&characterEncoding=utf-8
    username: root
