dubbo:
  application:
    name: paygw
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.pajk.pay.service
logging:
  level:
    com:
      pajk:
        payment: DEBUG
    root: INFO
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pajk.payment.entity
server:
  port: 8084
spring:
  application:
    name: paygw
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/paygw?useSSL=false&characterEncoding=utf-8
    username: root
